ci: prevent detox E2E lock failure (#11186)
<!--
Please submit this PR as a draft initially.
Do not mark it as "Ready for review" until the template has been
completely filled out, and PR status checks have passed at least once.
-->

## **Description**

The purpose of this PR is to address the recent flakiness we noticed in
CI as it relates to detox failing with this type of error:

```
/Users/vagrant/git/node_modules/proper-lockfile/lib/lockfile.js:181
        onCompromised: (err) => { throw err; },
                                  ^
Error: Unable to update lock within the stale threshold
    at /Users/vagrant/git/node_modules/proper-lockfile/lib/lockfile.js:109:21
    at newFs.<computed> [as utimes] (/Users/vagrant/git/node_modules/proper-lockfile/lib/adapter.js:20:13)
    at Timeout._onTimeout (/Users/vagrant/git/node_modules/proper-lockfile/lib/lockfile.js:100:20)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7) {
  code: 'ECOMPROMISED'
}
```

This issue is on Detox's side. To remedy the issue I did two main
things:

1. I applied a patch to Detox's Node module to help reduce test failures
caused by the above failure. I increased the lock timeout to 20 seconds.
2. Before each run, I reset the detox lock file: `detox
reset-lock-file`.
 
 
 
 After three runs on Bitrise
-
https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/782c9740-e8f3-4e5f-a0ac-e0b553328e11
-
https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/93cdcfd5-9c2b-4cfa-ad18-c06dd38a6ea8
-
https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/a52569c4-b3fc-4779-b568-3b7b192c18d1


, the pipeline seemed much more stable than the main branch, which
failed on every run.


## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
7.
8.

## **Screenshots/Recordings**

<!-- If applicable, add screenshots and/or recordings to visualize the
before and after of your change. -->

### **Before**

<!-- [screenshots/recordings] -->

### **After**

<!-- [screenshots/recordings] -->

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor
Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile
Coding
Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format
if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling
guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)).
Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the
app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described
in the ticket it closes and includes the necessary testing evidence such
as recordings and or screenshots.